"""
Claude 深度清洗腳本 for Code Review Fine-tuning Data
=====================================================
Multi-pass cleaning pipeline:
  Pass 1: Bot / automated comment removal
  Pass 2: Low-quality output removal
  Pass 3: Gerrit boilerplate removal
  Pass 4: Non-review content removal (welcomes, closings, templates)
  Pass 5: Question-only with no review value
  Pass 6: Input quality (truncation, no-code removal)
  Pass 7: Output normalization & cleanup
  Pass 8: Deduplication (exact + near-duplicate)
  Pass 9: Final validation
"""

import json
import re
from collections import Counter

INPUT_PATH = "combined_training_data.json"
OUTPUT_PATH = "claude_cleaned_training_data.json"

# ── Load ────────────────────────────────────────────────────────────────

with open(INPUT_PATH, encoding="utf-8") as f:
    data = json.load(f)

print(f"載入 {len(data)} 筆資料")
print("=" * 70)

# ── Tracking ────────────────────────────────────────────────────────────

removed_reasons = Counter()
removed_indices = set()


def remove(idx, reason):
    if idx not in removed_indices:
        removed_indices.add(idx)
        removed_reasons[reason] += 1


# ═══════════════════════════════════════════════════════════════════════
# PASS 1: Bot / Automated Comment Removal
# ═══════════════════════════════════════════════════════════════════════

print("Pass 1: Bot / automated comment detection...")

for i, d in enumerate(data):
    out_lower = d["output"].strip().lower()

    # sqla-tester bot
    if "sqla-tester" in out_lower or "setting up my work on behalf of" in out_lower:
        remove(i, "bot:sqla-tester")
        continue

    # GitHub Copilot reviews
    if "copilot reviewed" in out_lower or "copilot wasn't able" in out_lower \
       or "copilot encountered" in out_lower:
        remove(i, "bot:copilot")
        continue

    # Copilot "Pull request overview" format
    if out_lower.startswith("## pull request overview"):
        remove(i, "bot:copilot_pr_overview")
        continue

    # Other bots
    bot_keywords = [
        "codecov report", "coverage decreased", "coverage increased",
        "codecov/project", "codecov/patch", "dependabot",
        "renovate bot", "stale bot", "mergify",
        "auto-generated by", "automatically generated",
        "sonarqube", "sonarcloud", "codefactor", "codeclimate",
        "🚀 deployed to", "deploy preview",
    ]
    if any(kw in out_lower for kw in bot_keywords):
        remove(i, "bot:other_automated")
        continue

print(f"  Bot removed: {sum(v for k, v in removed_reasons.items() if k.startswith('bot:'))}")

# ═══════════════════════════════════════════════════════════════════════
# PASS 2: Low-quality Output Removal
# ═══════════════════════════════════════════════════════════════════════

print("Pass 2: Low-quality output removal...")

for i, d in enumerate(data):
    if i in removed_indices:
        continue

    out = d["output"].strip()
    out_lower = out.lower()
    src = d["metadata"]["source"]

    # Skip handcrafted — they are structured JSON, different rules
    if src == "handcrafted":
        continue

    # --- Too short (< 25 chars) ---
    if len(out) < 25:
        remove(i, "low_quality:too_short")
        continue

    # --- Just a URL ---
    if re.match(r"^https?://\S+$", out):
        remove(i, "low_quality:just_url")
        continue

    # --- Bare code suggestion with no explanation ---
    if out.startswith("```suggestion"):
        text_outside = re.sub(r"```.*?```", "", out, flags=re.DOTALL).strip()
        if len(text_outside) < 15:
            remove(i, "low_quality:bare_suggestion")
            continue

    # --- Trivial one-word responses ---
    stripped = re.sub(r"[^\w\s]", "", out_lower).strip()
    trivial_responses = {
        "done", "fixed", "will do", "will fix", "acknowledged", "ack",
        "yes", "no", "sure", "ok", "okay", "right", "correct",
        "makes sense", "i see", "got it", "thanks", "thank you", "ty",
        "agreed", "nice", "cool", "great", "awesome",
        "good point will update", "good point will fix",
        "good catch", "good catch thanks", "good catch thank you",
    }
    if stripped in trivial_responses:
        remove(i, "low_quality:trivial_response")
        continue

    # --- Commit hash reference only ---
    if re.match(r"^(fix(ed)?|done)\s+(with|in)\s+[a-f0-9]{7,}", out_lower):
        remove(i, "low_quality:commit_hash_only")
        continue

print(f"  Low-quality removed: {sum(v for k, v in removed_reasons.items() if k.startswith('low_quality:'))}")

# ═══════════════════════════════════════════════════════════════════════
# PASS 3: Gerrit Boilerplate Removal
# ═══════════════════════════════════════════════════════════════════════

print("Pass 3: Gerrit boilerplate removal...")

for i, d in enumerate(data):
    if i in removed_indices:
        continue

    out = d["output"].strip()
    out_lower = out.lower()

    if "view this in gerrit at https://gerrit" in out_lower:
        # Extract actual review content (before gerrit link)
        actual = re.split(r"view this in gerrit", out, flags=re.IGNORECASE)[0].strip()
        # Remove "**Name** (user) wrote:" prefix
        actual = re.sub(r"\*\*.*?\*\*\s*\(.*?\)\s*wrote:\s*", "", actual).strip()

        if len(actual) < 40:
            remove(i, "gerrit:boilerplate_minimal")
        else:
            # Keep it but we'll clean the gerrit suffix in Pass 7
            pass

print(f"  Gerrit boilerplate removed: {removed_reasons.get('gerrit:boilerplate_minimal', 0)}")

# ═══════════════════════════════════════════════════════════════════════
# PASS 4: Non-review Content Removal
# ═══════════════════════════════════════════════════════════════════════

print("Pass 4: Non-review content removal...")

for i, d in enumerate(data):
    if i in removed_indices:
        continue

    out = d["output"].strip()
    out_lower = out.lower()
    src = d["metadata"]["source"]

    if src == "handcrafted":
        continue

    # --- Welcome/greeting messages (not actual reviews) ---
    if re.search(r"hello!?\s+thank you for your contribution", out_lower):
        remove(i, "non_review:welcome_greeting")
        continue

    # --- PR closing/spam messages ---
    if re.search(
        r"(i'?m closing this (pr|pull request)|closing this as (spam|duplicate|stale))",
        out_lower,
    ):
        remove(i, "non_review:pr_closing")
        continue

    # --- Unfilled PR templates ---
    if out.startswith("<!--") and out.count("<!--") >= 2:
        remove(i, "non_review:markdown_template")
        continue

    # --- "Thank you for your interest" + closing pattern ---
    if re.search(r"thank you for your interest in contributing.*closing", out_lower, re.DOTALL):
        remove(i, "non_review:contribution_closing")
        continue

print(f"  Non-review removed: {sum(v for k, v in removed_reasons.items() if k.startswith('non_review:'))}")

# ═══════════════════════════════════════════════════════════════════════
# PASS 5: Weak Question-only Comments
# ═══════════════════════════════════════════════════════════════════════

print("Pass 5: Weak question-only comments...")

for i, d in enumerate(data):
    if i in removed_indices:
        continue

    out = d["output"].strip()
    out_lower = out.lower()
    src = d["metadata"]["source"]

    if src == "handcrafted":
        continue

    # Very short questions with no review substance
    # Keep questions that are actually good review (e.g., "shouldn't this use X?", "why not use Y?")
    if len(out) < 50 and out.endswith("?"):
        # These patterns indicate genuine review questions — keep them
        good_question_patterns = [
            "should", "shouldn't", "could", "why not", "what about",
            "consider", "instead", "better", "rather", "prefer",
            "necessary", "needed", "redundant", "missing", "unused",
        ]
        has_review_value = any(p in out_lower for p in good_question_patterns)
        if not has_review_value:
            # Truly weak: "can you please cross check this?", "What happened?"
            if re.match(
                r"^(can you|what|how|where|when|who|is this|are these|does this|did)",
                out_lower,
            ):
                remove(i, "weak_question:no_review_value")

print(f"  Weak questions removed: {removed_reasons.get('weak_question:no_review_value', 0)}")

# ═══════════════════════════════════════════════════════════════════════
# PASS 6: Input Quality
# ═══════════════════════════════════════════════════════════════════════

print("Pass 6: Input quality checks...")

input_truncated = 0
MAX_INPUT_LEN = 4000  # Generous but bounded

for i, d in enumerate(data):
    if i in removed_indices:
        continue

    inp = d["input"].strip()

    # Remove entries with no meaningful input
    if len(inp) < 10:
        remove(i, "input:too_short")
        continue

    # Truncate very long inputs (keep entry, just trim)
    if len(inp) > MAX_INPUT_LEN:
        d["input"] = inp[:MAX_INPUT_LEN]
        input_truncated += 1

print(f"  Input too short removed: {removed_reasons.get('input:too_short', 0)}")
print(f"  Input truncated (kept): {input_truncated}")

# ═══════════════════════════════════════════════════════════════════════
# PASS 7: Output Normalization & Cleanup
# ═══════════════════════════════════════════════════════════════════════

print("Pass 7: Output normalization...")

normalized_count = 0

for i, d in enumerate(data):
    if i in removed_indices:
        continue

    out = d["output"]
    original = out
    src = d["metadata"]["source"]

    if src == "handcrafted":
        continue

    # Clean Gerrit suffix from entries we're keeping
    if "View this in Gerrit at https://gerrit" in out:
        out = re.split(r"\s*View this in Gerrit at https://gerrit", out)[0].strip()
        # Also clean "**Name** (user) wrote:" prefix
        out = re.sub(r"^\*\*.*?\*\*\s*\(.*?\)\s*wrote:\s*\n*", "", out).strip()

    # Remove trailing whitespace / excessive newlines
    out = re.sub(r"\n{3,}", "\n\n", out)
    out = out.strip()

    # If cleaning emptied the output, remove entry
    if not out or len(out) < 20:
        remove(i, "normalized_to_empty")
        continue

    if out != original:
        d["output"] = out
        normalized_count += 1

print(f"  Outputs normalized: {normalized_count}")
print(f"  Normalized to empty (removed): {removed_reasons.get('normalized_to_empty', 0)}")

# ═══════════════════════════════════════════════════════════════════════
# PASS 8: Deduplication
# ═══════════════════════════════════════════════════════════════════════

print("Pass 8: Deduplication...")

# Exact dedup on output text (keep first occurrence)
seen_outputs = {}
dedup_count = 0

for i, d in enumerate(data):
    if i in removed_indices:
        continue

    key = d["output"].strip().lower()

    if key in seen_outputs:
        remove(i, "duplicate:exact_output")
        dedup_count += 1
    else:
        seen_outputs[key] = i

# Near-dedup: outputs that share the first 150 chars (and are < 200 chars total)
seen_prefixes = {}
for i, d in enumerate(data):
    if i in removed_indices:
        continue

    out = d["output"].strip().lower()
    if len(out) < 200:
        prefix = out[:150]
        if prefix in seen_prefixes:
            remove(i, "duplicate:near_output")
            dedup_count += 1
        else:
            seen_prefixes[prefix] = i

print(f"  Duplicates removed: {dedup_count}")

# ═══════════════════════════════════════════════════════════════════════
# PASS 9: Final Validation
# ═══════════════════════════════════════════════════════════════════════

print("Pass 9: Final validation...")

# Build cleaned list
cleaned = []
for i, d in enumerate(data):
    if i in removed_indices:
        continue

    # Final checks
    if not d.get("instruction") or not d.get("input") or not d.get("output"):
        remove(i, "validation:missing_field")
        continue

    if len(d["output"].strip()) < 20 and d["metadata"]["source"] != "handcrafted":
        remove(i, "validation:output_still_short")
        continue

    cleaned.append(d)

# ═══════════════════════════════════════════════════════════════════════
# Report & Save
# ═══════════════════════════════════════════════════════════════════════

print("\n" + "=" * 70)
print("清洗報告")
print("=" * 70)
print(f"\n原始資料：{len(data)} 筆")
print(f"移除總計：{len(removed_indices)} 筆")
print(f"清洗後：  {len(cleaned)} 筆")

print(f"\n移除原因明細：")
for reason, count in removed_reasons.most_common():
    print(f"  {reason}: {count}")

# Source distribution after cleaning
print(f"\n清洗後來源分佈：")
sources = Counter(d["metadata"]["source"] for d in cleaned)
for src, count in sources.most_common():
    print(f"  {src}: {count}")

# Repo distribution after cleaning
print(f"\n清洗後 Repo 分佈：")
repos = Counter(d["metadata"].get("repo", "synthetic") for d in cleaned)
for repo, count in repos.most_common():
    print(f"  {repo}: {count}")

# Length stats after cleaning
input_lens = [len(d["input"]) for d in cleaned]
output_lens = [len(d["output"]) for d in cleaned]
print(f"\n清洗後長度統計：")
print(f"  Input  - avg:{sum(input_lens)//len(input_lens)} med:{sorted(input_lens)[len(input_lens)//2]} max:{max(input_lens)} min:{min(input_lens)}")
print(f"  Output - avg:{sum(output_lens)//len(output_lens)} med:{sorted(output_lens)[len(output_lens)//2]} max:{max(output_lens)} min:{min(output_lens)}")

# Save
with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    json.dump(cleaned, f, ensure_ascii=False, indent=2)

print(f"\n✅ 儲存到 {OUTPUT_PATH}")
